# Project-wide Gradle settings.
org.gradle.configureondemand=true
org.gradle.caching=true
org.gradle.parallel=true
#org.gradle.jvmargs=-Xmx1536m
org.gradle.unsafe.configuration-cache=true
# AndroidX
android.useAndroidX=true
# Allow data binding to be incremental
#android.databinding.incremental=true
kapt.incremental.apt=true
kapt.include.compile.classpath=false
kapt.use.worker.api=false
org.gradle.jvmargs=-Xmx2048m --add-exports jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED
# Signing Config
STORE_FILE=keystore.jks
STORE_PASSWORD=27072000
KEY_ALIAS=mckimquyen
KEY_PASSWORD=27072000

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true

# Gradle JVM (Gradle 8.11.1 support Java 8-23, JDK 25 khong tuong thich)
org.gradle.java.home=/Users/loitran/Library/Java/JavaVirtualMachines/jbr-17.0.14/Contents/Home
