package com.galaxyjoy.cpuinfo.feat.p2pcompare

import com.google.gson.Gson

/**
 * U22 P2P Device Compare — the text code shared between 2 real devices. `version` is carried
 * along (not enforced yet, only 1 version exists) so a future field change can add migration
 * logic without breaking codes generated by an older app version.
 */
data class DeviceComparePayload(
    val version: Int,
    val deviceModel: String,
    val ramBytes: Long,
    val storageBytes: Long,
) {
    companion object {
        private const val CURRENT_VERSION = 1
        private val gson = Gson()

        fun create(deviceModel: String, ramBytes: Long, storageBytes: Long) =
            DeviceComparePayload(CURRENT_VERSION, deviceModel, ramBytes, storageBytes)

        fun encode(payload: DeviceComparePayload): String = gson.toJson(payload)

        /**
         * Never throws — a pasted code can be anything (empty, garbage text, JSON missing a
         * field). Gson deserializes via reflection, bypassing Kotlin's constructor null-checks,
         * so a missing field can leave a `null` in a non-null-typed property; the validation
         * below runs inside the same try so a resulting NPE is caught too, not just JSON syntax
         * errors.
         */
        fun decode(code: String): DeviceComparePayload? = try {
            val payload = gson.fromJson(code.trim(), DeviceComparePayload::class.java)
            when {
                payload == null -> null
                payload.deviceModel.isBlank() -> null
                payload.ramBytes <= 0 -> null
                payload.storageBytes <= 0 -> null
                else -> payload
            }
        } catch (e: Exception) {
            null
        }
    }
}
