package com.galaxyjoy.cpuinfo.util

import android.content.Context
import android.content.Intent
import android.os.Build
import android.os.Environment
import com.galaxyjoy.cpuinfo.data.provider.DataProviderCpu
import com.galaxyjoy.cpuinfo.data.provider.DataProviderGpu
import com.galaxyjoy.cpuinfo.data.provider.DataProviderRam
import com.galaxyjoy.cpuinfo.data.provider.DataNativeProviderCpu
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import javax.inject.Inject

class SystemInfoExporter @Inject constructor(
    private val dataProviderCpu: DataProviderCpu,
    private val dataProviderRam: DataProviderRam,
    private val dataProviderGpu: DataProviderGpu,
    private val dataNativeProviderCpu: DataNativeProviderCpu,
    private val dispatchersProvider: DispatchersProvider
) {

    fun exportSystemInfo(context: Context) {
        CoroutineScope(Dispatchers.Main).launch {
            val systemInfo = withContext(dispatchersProvider.io) {
                buildSystemInfoText()
            }

            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_SUBJECT, "System Information - ${Build.MODEL}")
                putExtra(Intent.EXTRA_TEXT, systemInfo)
            }

            context.startActivity(Intent.createChooser(shareIntent, "Share System Info"))
        }
    }

    @Suppress("DEPRECATION")
    private fun buildSystemInfoText(): String {
        return buildString {
            appendLine("=== SYSTEM INFORMATION ===")
            appendLine()

            // Device Info
            appendLine("📱 DEVICE")
            appendLine("Model: ${Build.MODEL}")
            appendLine("Brand: ${Build.BRAND}")
            appendLine("Manufacturer: ${Build.MANUFACTURER}")
            appendLine("Android: ${Build.VERSION.RELEASE} (API ${Build.VERSION.SDK_INT})")
            appendLine()

            // CPU Info
            appendLine("⚙️ CPU")
            appendLine("Processor: ${dataNativeProviderCpu.getCpuName()}")
            appendLine("ABI: ${dataProviderCpu.getAbi()}")
            appendLine("Cores: ${dataProviderCpu.getNumberOfCores()}")
            val cpuCount = dataProviderCpu.getNumberOfCores()
            for (i in 0 until cpuCount) {
                val freq = dataProviderCpu.getCurrentFreq(i)
                if (freq > 0) {
                    appendLine("Core $i: ${freq}MHz")
                }
            }
            appendLine()

            // RAM Info
            appendLine("💾 RAM")
            val totalRam = dataProviderRam.getTotalBytes() / (1024 * 1024 * 1024.0)
            val availRam = dataProviderRam.getAvailableBytes() / (1024 * 1024 * 1024.0)
            appendLine("Total: ${"%.2f".format(totalRam)}GB")
            appendLine("Available: ${"%.2f".format(availRam)}GB")
            appendLine("Usage: ${100 - dataProviderRam.getAvailablePercentage()}%")
            appendLine()

            // Storage Info
            appendLine("💿 STORAGE")
            val internalPath = Environment.getDataDirectory()
            val internalTotal = internalPath.totalSpace / (1024 * 1024 * 1024.0)
            val internalFree = internalPath.usableSpace / (1024 * 1024 * 1024.0)
            appendLine("Internal Total: ${"%.2f".format(internalTotal)}GB")
            appendLine("Internal Free: ${"%.2f".format(internalFree)}GB")
            appendLine()

            // GPU Info
            appendLine("🎮 GPU")
            appendLine("GLES Version: ${dataProviderGpu.getGlEsVersion()}")
            appendLine("Vulkan Version: ${dataProviderGpu.getVulkanVersion()}")
            appendLine()

            appendLine("Generated by CPU Info App")
        }
    }
}
